name: iit_iaa_project

services:
  iit_project:
    image: superslayer4/iit_project:api
    container_name: iit_iaa_backend_container
    env_file: 
      - .env-container
    ports:
      - "8001:8000"
    volumes:
      - ".:/backend"
  postgres:
    image: postgres
    container_name: iit_iaa_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  
